export default {
    isFormElement: true,
    isContainer: false,
    fields: [
        {label: '可清除', category: '选项', field: 'allowClear', type: 'boolean', defaultValue: false, version: '', desc: '显示清除按钮'},
        {label: '可搜索', category: '选项', field: 'showSearch', type: 'boolean', defaultValue: '单选：false | 多选：true', version: '', desc: '是否支持搜索框'},
        {label: '边框', category: '选项', field: 'bordered', type: 'boolean', defaultValue: true, version: '', desc: '是否显示边框'},
        {label: '禁用', category: '选项', field: 'disabled', type: 'boolean', defaultValue: false, version: '', desc: '是否禁用'},
        {label: '多选', category: '选项', field: 'multiple', type: 'boolean', defaultValue: false, version: '', desc: '支持多选（当设置 treeCheckable 时自动变为 true）'},
        {label: '选框', category: '选项', field: 'treeCheckable', type: 'boolean', defaultValue: false, version: '', desc: '显示 Checkbox'},
        {label: '输入框提示', field: 'placeholder', type: 'string', version: '', desc: '选择框默认文字'},
        {
            label: '控件大小', field: 'size', type: 'radio-group', version: '',
            options: [
                {value: 'large', label: '大号'},
                {value: 'middle', label: '中号'},
                {value: 'small', label: '小号'},
            ],
        },
    ],
};
/*
[
    {label:'显示清除按钮',field:'allowClear',type:'boolean',defaultValue:false,version:'',desc:'显示清除按钮'},
    {label:'当多选模式下值被选择，自动清空搜索框',field:'autoClearSearchValue',type:'boolean',defaultValue:true,version:'',desc:'当多选模式下值被选择，自动清空搜索框'},
    {label:'是否显示边框',field:'bordered',type:'boolean',defaultValue:true,version:'',desc:'是否显示边框'},
    {label:'指定默认选中的条目',field:'defaultValue',type:'radio-group',version:'',options:[{value:'string',label:'string'},{value:'string[]',label:'string[]'}],desc:'指定默认选中的条目'},
    {label:'是否禁用',field:'disabled',type:'boolean',defaultValue:false,version:'',desc:'是否禁用'},
    {label:'下拉菜单的 className 属性',field:'dropdownClassName',type:'string',version:'',desc:'下拉菜单的 className 属性'},
    {label:'下拉菜单和选择器同宽。默认将设置 min-width，当值小于选择框宽度时会被忽略。false 时会关闭虚拟滚动',field:'dropdownMatchSelectWidth',type:'radio-group',defaultValue:true,version:'',options:[{value:'boolean',label:'boolean'},{value:'number',label:'number'}],desc:'下拉菜单和选择器同宽。默认将设置 min-width，当值小于选择框宽度时会被忽略。false 时会关闭虚拟滚动'},
    {label:'自定义下拉框内容',field:'dropdownRender',type:'(originNode: ReactNode, props) => ReactNode',version:'',desc:'自定义下拉框内容'},
    {label:'下拉菜单的样式',field:'dropdownStyle',type:'object',version:'',desc:'下拉菜单的样式'},
    {label:'是否根据输入项进行筛选，默认用 treemultipleNodeFilterProp 的值作为要筛选的 TreeNode 的属性值',field:'filterTreeNode',type:'radio-group',defaultValue:'function',version:'',options:[{value:'boolean',label:'boolean'},{value:'function(inputValue: string, treeNode: TreeNode) (函数需要返回 bool 值)',label:'function(inputValue: string, treeNode: TreeNode) (函数需要返回 bool 值)'}],desc:'是否根据输入项进行筛选，默认用 treeNodeFilterProp 的值作为要筛选的 TreeNode 的属性值'},
    {label:'菜单渲染父节点。默认渲染到 body 上，如果你遇到菜单滚动定位问题，试试修改为滚动的区域，并相对其定位。示例',field:'getPopupContainer',type:'function(triggerNode)',defaultValue:'() => document.body',version:'',desc:'菜单渲染父节点。默认渲染到 body 上，如果你遇到菜单滚动定位问题，试试修改为滚动的区域，并相对其定位。示例'},
    {label:'是否把每个选项的 label 包装到 value 中，会把 value 类型从 string 变为 {value: string, label: ReactNode, halfChecked(treeCheckStrictly 时有效): string[] } 的格式',field:'labelInValue',type:'boolean',defaultValue:false,version:'',desc:'是否把每个选项的 label 包装到 value 中，会把 value 类型从 string 变为 {value: string, label: ReactNode, halfChecked(treeCheckStrictly 时有效): string[] } 的格式'},
    {label:'设置弹窗滚动高度',field:'listHeight',type:'number',defaultValue:'256',version:'',desc:'设置弹窗滚动高度'},
    {label:'异步加载数据',field:'loadData',type:'function(node)',version:'',desc:'异步加载数据'},
    {label:'最多显示多少个 tag，响应式模式会对性能产生损耗',field:'maxTagCount',type:'radio-group',version:'responsive: 4.10',options:[{value:'number',label:'number'},{value:'responsive',label:'responsive'}],desc:'最多显示多少个 tag，响应式模式会对性能产生损耗'},
    {label:'隐藏 tag 时显示的内容',field:'maxTagPlaceholder',type:'radio-group',version:'',options:[{value:'ReactNode',label:'ReactNode'},{value:'function(omittedValues)',label:'function(omittedValues)'}],desc:'隐藏 tag 时显示的内容'},
    {label:'支持多选（当设置 treeCheckable 时自动变为 true）',field:'multiple',type:'boolean',defaultValue:false,version:'',desc:'支持多选（当设置 treeCheckable 时自动变为 true）'},
    {label:'选择框默认文字',field:'placeholder',type:'string',version:'',desc:'选择框默认文字'},
    {label:'搜索框的值，可以通过 onSearch 获取用户输入',field:'searchValue',type:'string',version:'',desc:'搜索框的值，可以通过 onSearch 获取用户输入'},
    {label:'是否显示 suffixIcon，单选模式下默认 true',field:'showArrow',type:'boolean',version:'',desc:'是否显示 suffixIcon，单选模式下默认 true'},
    {label:'配置 treeCheckable 时，定义选中项回填的方式。TreeSelect.SHOW_ALL: 显示所有选中节点(包括父节点)。TreeSelect.SHOW_PARENT: 只显示父节点(当父节点下所有子节点都选中时)。 默认只显示子节点',field:'showCheckedStrategy',type:'radio-group',defaultValue:'TreeSelect.SHOW_CHILD',version:'',options:[{value:'TreeSelect.SHOW_ALL',label:'TreeSelect.SHOW_ALL'},{value:'TreeSelect.SHOW_PARENT',label:'TreeSelect.SHOW_PARENT'},{value:'TreeSelect.SHOW_CHILD',label:'TreeSelect.SHOW_CHILD'}],desc:'配置 treeCheckable 时，定义选中项回填的方式。TreeSelect.SHOW_ALL: 显示所有选中节点(包括父节点)。TreeSelect.SHOW_PARENT: 只显示父节点(当父节点下所有子节点都选中时)。 默认只显示子节点'},
    {label:'是否支持搜索框',field:'showSearch',type:'boolean',defaultValue:'单选：false | 多选：true',version:'',desc:'是否支持搜索框'},
    {label:'选择框大小',field:'size',type:'radio-group',version:'',options:[{value:'large',label:'large'},{value:'middle',label:'middle'},{value:'small',label:'small'}],desc:'选择框大小'},
    {label:'自定义的选择框后缀图标, 多选模式下必须同时设置 showArrow 为 true',field:'suffixIcon',type:'ReactNode',version:'',desc:'自定义的选择框后缀图标, 多选模式下必须同时设置 showArrow 为 true'},
    {label:'自定义树节点的展开/折叠图标',field:'switcherIcon',type:'ReactNode',version:'',desc:'自定义树节点的展开/折叠图标'},
    {label:'显示 Checkbox',field:'treeCheckable',type:'boolean',defaultValue:false,version:'',desc:'显示 Checkbox'},
    {label:'checkable 状态下节点选择完全受控（父子节点选中状态不再关联），会使得 labelInValue 强制为 true',field:'treeCheckStrictly',type:'boolean',defaultValue:false,version:'',desc:'checkable 状态下节点选择完全受控（父子节点选中状态不再关联），会使得 labelInValue 强制为 true'},
    {label:'treeNodes 数据，如果设置则不需要手动构造 TreeNode 节点（value 在整个树范围内唯一）',field:'treeData',type:'array<{value, title, children, [disabled, disableCheckbox, selectable, checkable]}>',defaultValue:'[]',version:'',desc:'treeNodes 数据，如果设置则不需要手动构造 TreeNode 节点（value 在整个树范围内唯一）'},
    {label:'使用简单格式的 treeData，具体设置参考可设置的类型 (此时 treeData 应变为这样的数据结构: [{id:1, pId:0, value:'1', title:\\'test1\\',...},...]， pId 是父节点的 id)',field:'treeDataSimpleMode',type:'radio-group',defaultValue:'false',version:'',options:[{value:'false',label:'false'},{value:'object<{ id: string, pId: string, rootPId: string }>',label:'object<{ id: string, pId: string, rootPId: string }>'}],desc:'使用简单格式的 treeData，具体设置参考可设置的类型 (此时 treeData 应变为这样的数据结构: [{id:1, pId:0, value:'1', title:\\'test1\\',...},...]， pId 是父节点的 id)'},
    {label:'默认展开所有树节点',field:'treeDefaultExpandAll',type:'boolean',defaultValue:false,version:'',desc:'默认展开所有树节点'},
    {label:'默认展开的树节点',field:'treeDefaultExpandedKeys',type:'string[]',version:'',desc:'默认展开的树节点'},
    {label:'设置展开的树节点',field:'treeExpandedKeys',type:'string[]',version:'',desc:'设置展开的树节点'},
    {label:'是否展示 TreeNode title 前的图标，没有默认样式，如设置为 true，需要自行定义图标相关样式',field:'treeIcon',type:'boolean',defaultValue:false,version:'',desc:'是否展示 TreeNode title 前的图标，没有默认样式，如设置为 true，需要自行定义图标相关样式'},
    {label:'输入项过滤对应的 treeNode 属性',field:'treeNodeFilterProp',type:'string',defaultValue:'value',version:'',desc:'输入项过滤对应的 treeNode 属性'},
    {label:'作为显示的 prop 设置',field:'treeNodeLabelProp',type:'string',defaultValue:'title',version:'',desc:'作为显示的 prop 设置'},
    {label:'指定当前选中的条目',field:'value',type:'radio-group',version:'',options:[{value:'string',label:'string'},{value:'string[]',label:'string[]'}],desc:'指定当前选中的条目'},
    {label:'设置 false 时关闭虚拟滚动',field:'virtual',type:'boolean',defaultValue:true,version:'4.1.0',desc:'设置 false 时关闭虚拟滚动'},
    {label:'选中树节点时调用此函数',field:'onChange',type:'function(value, label, extra)',version:'',desc:'选中树节点时调用此函数'},
    {label:'展开下拉菜单的回调',field:'onDropdownVisibleChange',type:'function(open)',version:'',desc:'展开下拉菜单的回调'},
    {label:'文本框值变化时回调',field:'onSearch',type:'function(value: string)',version:'',desc:'文本框值变化时回调'},
    {label:'被选中时调用',field:'onSelect',type:'function(value, node, extra)',version:'',desc:'被选中时调用'},
    {label:'展示节点时调用',field:'onTreeExpand',type:'function(expandedKeys)',version:'',desc:'展示节点时调用'}
]
* */
